export const FOOD_TYPES = [
  'Indian Food',
  'Chinese Food',
  'Thai Food',
  'Takeaway',
  'Pizza',
  'Asian Food',
  'Noodle',
  'Hamburger',
  'Italian Food',
  'Chicken',
  'Mexican Food',
  'Healthy Food',
  'Seafood',
  'Korean Food',
  'Vegan',
  'Vegetarian',
]
